### ISSUE TITLE
Does not completely fill the screen

### ISSUE THREAD

**Issue by farnasirim** [marcofugaro/threejs-modern-app#13]
Hi, first I'd like to thank you for this, very useful.

Using google chrome on gnome with 200% scaling, I can see a border of size 1 (?) pixel on the right and bottom sides of the screen. If I switch to fullscreen mode, only the one on the right side of the screen remains.

I know this is naive and don't intend to suggest this as a solution but while playing around a little with things, this seems to make it look like it works:
```
     width = window.innerWidth + 1;
     height = window.innerHeight + 1;
```
Screenshots debug utility both look fine to me after zooming in, the one after is one pixel wider/taller obviously.
before adding the above:
![default](https://user-images.githubusercontent.com/8123364/177684422-fa4fafa7-f4b0-40aa-adff-3d65052727c5.png)

after:
![after-plus-one-to-sizes](https://user-images.githubusercontent.com/8123364/177683814-4ed9c1c8-4dbe-400e-b905-dc3d23843240.png)

Some system screenshots to show what I see:
default: (note the border on the right side)
![default](https://user-images.githubusercontent.com/8123364/177685318-05fa7775-fb49-447b-8203-57f0be02bdf5.png)

after adding + 1 to sizes:
![size-plus-one](https://user-images.githubusercontent.com/8123364/177685323-283724a8-2be6-4f2e-8e15-3617cd73a902.png)

default code, but turned off gnome scaling. This looks ok to me
![no-scaling](https://user-images.githubusercontent.com/8123364/177685894-a62502fe-6159-48af-a36f-017fd107691b.png)

This doesn't happen on firefox. Cannot test on chromium on this machine right now. So the combination is:
* gnome
* 4k monitor
* 200% scaling
* google chrome

I'm keen to know what you think.
Thanks again

**Comment by marcofugaro** [comment]
Hey, this looks like it's related to the browser (Chrome) having some precision errors when scaling is enabled. So `window.innerWidth` does not match the actual screen size.

Unfortunately, I don't think there is really anything you can do about this.
