### ISSUE TITLE
Best way to enable Orbit Controller in production mode (without debug)

### ISSUE THREAD

**Issue by lalamax3d** [marcofugaro/threejs-modern-app#4]
Hi,
thanks for such a nice starter point. 
Q. i can put ?debug and orbit controller works. Sorry slightly newbie to all this. what is best way to enable this without debug (as in final application) thanks in advance.

**Comment by marcofugaro** [comment]
Hey, totally missed your question, you just have to remove the `window.DEBUG` check from this line:

https://github.com/marcofugaro/threejs-modern-app/blob/ef8922348b884fa6952844772e6e8000775b5413/src/index.js#L31

so ti becomes 

```js
orbitControls: { distance: 5 },
```
