### ISSUE TITLE
Textures fail to load after page is refreshed

### ISSUE THREAD

**Issue by joinemm** [marcofugaro/threejs-modern-app#9]
Running the example code with `yarn start` everything works fine, until I refresh the page. Then all the textures turn black and I get bunch of these errors in the console:

`THREE.WebGLRenderer: Texture marked for update but image is incomplete`

Closing the tab and reopening it in new tab seems to fix the issue. Using Firefox on Linux.

**Comment by marcofugaro** [comment]
Fixed with bd303c968c0b0ef56a40046e054371ba4b8c7e54!
